"""One-time migration from the legacy `~/.codex-shared` runtime (Codex-only router + `~/.claude` shims) to agent-harness.

Keeps the legacy design invariants: `.codex-shared\\AGENTS.md` stays the single policy file (the harness policy becomes
one more hard link to it), profile `hooks.json` files stay hard links to `.codex-shared\\hooks.json`, and profile
`config.toml` files stay generated by `sync-global.cmd` (the OTel exporter goes into `config\\common.toml`).

Usage: python -m scripts.migrate_codex_shared --env-file <.env> [--apply]   (default: dry run, prints the plan)
Rollback: every touched file is copied to <HARNESS_HOME>\\var\\backups\\migrate-<ts>\\ first; `compile` keeps its own.
"""
from __future__ import annotations

import copy
import json
import os
import shutil
import subprocess
import sys
import tomllib
from datetime import datetime
from pathlib import Path
from typing import Any, Mapping

from adapters.codex import patches as codex_patches
from core.config import Config, load

ROOT = Path(__file__).resolve().parents[1]
LEGACY_SHIMS = ("notify-gate.ps1", "obs-hook.ps1", "background_tasks.py", "claude_otel_receiver.py", "claude_turn_usage.py")
LEGACY_IMPORT = "@~/.codex-shared/AGENTS.md"
# Python processes only, never this PowerShell (its own command line contains the pattern).
STOP_LEGACY_RECEIVER = ("Get-CimInstance Win32_Process -Filter \"Name like 'python%'\" | "
                        "Where-Object { $_.ProcessId -ne $PID -and $_.CommandLine -like '*claude_otel_receiver.py*' } | "
                        "ForEach-Object { Stop-Process -Id $_.ProcessId -Force; $_.ProcessId }")
HIDDEN = int(getattr(subprocess, "CREATE_NO_WINDOW", 0))


def retire_claude_shims(settings: Mapping[str, Any]) -> tuple[dict, int]:
    """Settings without hook commands that call the legacy ~/.claude shims; returns (new settings, removed count)."""
    out = copy.deepcopy(dict(settings))
    removed, hooks = 0, {}
    for event, groups in (out.get("hooks") or {}).items():
        kept_groups = []
        for group in groups:
            entries = group.get("hooks", [])
            kept = [h for h in entries if not any(s in str(h.get("command", "")) for s in LEGACY_SHIMS)]
            removed += len(entries) - len(kept)
            if kept:
                kept_groups.append({**group, "hooks": kept})
        if kept_groups:
            hooks[event] = kept_groups
    if "hooks" in out:
        out["hooks"] = hooks
    return out, removed


def add_common_otel(common_text: str, endpoint: str) -> str:
    wanted = {"exporter": {"otlp-http": {"endpoint": endpoint, "protocol": "json"}}}
    existing = tomllib.loads(common_text).get("otel")
    if existing is not None:
        if existing == wanted:
            return common_text
        raise ValueError("common.toml already has a different [otel] table; resolve it by hand")
    table = f'\n[otel.exporter.otlp-http]\nendpoint = "{endpoint}"\nprotocol = "json"\n'
    return common_text.rstrip("\n") + "\n" + table


def drop_legacy_import(text: str) -> str:
    return "".join(line for line in text.splitlines(keepends=True) if line.strip() != LEGACY_IMPORT)


class Migration:
    def __init__(self, cfg: Config, env_file: Path, apply: bool):
        self.cfg, self.env_file, self.apply = cfg, env_file, apply
        self.shared = Path.home() / ".codex-shared"
        self.claude = [i.home for i in cfg.instances if i.agent == "claude"]
        self.codex = [i.home for i in cfg.instances if i.agent == "codex"]
        self.backup_root = cfg.harness_home / "var" / "backups" / f"migrate-{datetime.now():%Y%m%dT%H%M%S}"
        self.report: list[dict] = []

    def step(self, name: str, **details: Any) -> None:
        self.report.append({"step": name, "applied": self.apply, **details})

    def touched(self) -> list[Path]:
        files = [self.shared / "AGENTS.md", self.shared / "hooks.json", self.shared / "config" / "common.toml"]
        files += sorted((self.shared / "config" / "resolved").glob("*.toml"))
        for home in self.codex:
            files += [home / "hooks.json", home / "config.toml", home / "AGENTS.md"]
        for home in self.claude:
            files += [home / "settings.json", home / "CLAUDE.md"]
        return [f for f in files if f.exists()]

    def backup(self) -> None:
        files = self.touched()
        if self.apply:
            for path in files:
                destination = self.backup_root / path.relative_to(Path.home())
                destination.parent.mkdir(parents=True, exist_ok=True)
                shutil.copy2(path, destination)
        self.step("backup", files=len(files), root=str(self.backup_root))

    def seed_policy(self) -> None:
        policy = self.cfg.harness_home / "policy" / "AGENTS.md"
        if policy.exists():
            self.step("policy.seed", result="exists", linked=os.path.samefile(policy, self.shared / "AGENTS.md"))
            return
        if self.apply:
            policy.parent.mkdir(parents=True, exist_ok=True)
            os.link(self.shared / "AGENTS.md", policy)
        self.step("policy.seed", result="hard link to .codex-shared\\AGENTS.md")

    def common_otel(self) -> None:
        common = self.shared / "config" / "common.toml"
        endpoint = tomllib.loads(codex_patches.otel_block(self.cfg))["otel"]["exporter"]["otlp-http"]["endpoint"]
        text = common.read_text(encoding="utf-8")
        updated = add_common_otel(text, endpoint)
        if self.apply and updated != text:
            common.write_text(updated, encoding="utf-8")
            self._run([str(self.shared / "sync-global.cmd")], "sync-global")
            verify = self._run([sys.executable, str(self.shared / "config" / "sync_config.py"), "verify"], "sync verify")
            if json.loads(verify).get("status") != "ok":
                raise RuntimeError(f"sync_config verify failed: {verify[-400:]}")
        self.step("codex.common_otel", changed=updated != text, endpoint=endpoint)

    def stop_legacy_receiver(self) -> None:
        pids = self._run(["powershell.exe", "-NoProfile", "-Command", STOP_LEGACY_RECEIVER], "stop receiver") if self.apply else ""
        self.step("claude.legacy_receiver.stop", pids=pids.split())

    def claude_files(self) -> None:
        for home in self.claude:
            settings_path, claude_md = home / "settings.json", home / "CLAUDE.md"
            settings, removed = retire_claude_shims(json.loads(settings_path.read_text(encoding="utf-8")))
            md = claude_md.read_text(encoding="utf-8") if claude_md.exists() else ""
            new_md = drop_legacy_import(md)
            if self.apply:
                if removed:
                    settings_path.write_text(json.dumps(settings, indent=2, ensure_ascii=False) + "\n", encoding="utf-8")
                if new_md != md:
                    claude_md.write_text(new_md, encoding="utf-8")
            self.step("claude.retire_shims", home=str(home), removed=removed, legacy_import_dropped=new_md != md)

    def install(self) -> None:
        args = ["powershell.exe", "-NoProfile", "-ExecutionPolicy", "Bypass", "-File", str(ROOT / "scripts" / "install.ps1"),
                "-Destination", str(self.cfg.harness_home), "-EnvFile", str(self.env_file), "-Prerequisites", "ValidateOnly"]
        if not self.apply:
            args += ["-DryRun", "-CompileDryRun"]
        self._run(args, "install")
        self.step("install", destination=str(self.cfg.harness_home))

    def verify(self) -> None:
        same = os.path.samefile
        policy = self.cfg.harness_home / "policy" / "AGENTS.md"
        checks = {
            "policy_linked": policy.exists() and same(policy, self.shared / "AGENTS.md"),
            "codex_agents_linked": all(same(h / "AGENTS.md", self.shared / "AGENTS.md") for h in self.codex),
            "codex_hooks_linked": all(same(h / "hooks.json", self.shared / "hooks.json") for h in self.codex),
            "codex_hooks_routed": "harness-hook" in (self.shared / "hooks.json").read_text(encoding="utf-8"),
        }
        self.step("verify", **checks)
        if self.apply and not all(checks.values()):
            raise RuntimeError(f"verification failed: {checks}")

    def _run(self, args: list[str], label: str) -> str:
        env = {**os.environ, "PSModulePath": ""} if args[0].lower().startswith("powershell") else None
        done = subprocess.run(args, capture_output=True, text=True, encoding="utf-8", errors="replace",
                              timeout=900, creationflags=HIDDEN, env=env)
        if done.returncode != 0:
            raise RuntimeError(f"{label} failed ({done.returncode}): {(done.stderr or done.stdout)[-800:]}")
        return done.stdout.strip()

    def run(self) -> list[dict]:
        self.backup()
        self.seed_policy()
        self.common_otel()
        self.stop_legacy_receiver()
        self.claude_files()
        self.install()
        if self.apply:
            self.verify()
        return self.report


def main(argv: list[str] | None = None) -> int:
    args = list(sys.argv[1:] if argv is None else argv)
    env_file = Path(args[args.index("--env-file") + 1]) if "--env-file" in args else Path.home() / ".agent-harness" / ".env"
    migration = Migration(load(env_file, os.environ), env_file.resolve(), apply="--apply" in args)
    try:
        report = migration.run()
    except (RuntimeError, ValueError, OSError) as error:
        print(json.dumps({"outcome": "failed", "error": str(error), "steps": migration.report}, indent=1))
        return 1
    print(json.dumps({"outcome": "succeeded", "steps": report}, indent=1))
    return 0


if __name__ == "__main__":
    raise SystemExit(main())
